version: '3'

services:
  api:
    # image: flask_api:latest
    build: ./api
    # restart: on-failure
    volumes:
      - ./api:/app
    links:
      - db
    ports:
      - 8080:8080
  db:
    # image: mysql/mysql-server:latest
    build: ./db
    environment:
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: userdata
    ports:
      - 3306:3306